#!/bin/sh
cd ${0%/*} || exit 1

for path in [0-9]* [0-9]*.[0-9]*; do
    [ -e "$path" ] || continue
    case "$path" in
        0)
            continue
            ;;
    esac
    rm -rf "$path"
done

rm -rf constant/neutroRegion/polyMesh
rm -rf log.* *.log *.out
