#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf log.blockMesh log.checkMesh
runApplication blockMesh -case . -region neutroRegion
runApplication checkMesh -case . -region neutroRegion
