"""Frozen calibration constants derived from theory/reactorModel.ipynb Estimate 2.

Source: 2D r-z finite-difference one-group diffusion solver (dr = dz = 3 cm).
Reference state: clean unrodded core solved at the production mesh spacing.

Rod-worth table and critical insertion were regenerated by running solve_2d at
x = 0.0, 0.1, …, 1.0 with the current rod geometry (r_rod=50 cm, dSa=0.25 cm⁻¹)
to ensure point-kinetics and diffusion solver are self-consistent.
"""

# ---------------------------------------------------------------------------
# Estimate 2 geometry (cm)
# ---------------------------------------------------------------------------
ESTIMATE2_R_INNER_CM: float = 80.0
ESTIMATE2_R_FUEL_CM: float = 345.6
ESTIMATE2_R_REFL_CM: float = 405.6
ESTIMATE2_H_ACTIVE_CM: float = 691.2
ESTIMATE2_H_REFL_CM: float = 60.0  # per axial side

# ---------------------------------------------------------------------------
# Nominal operating point
# ---------------------------------------------------------------------------
# Approximate peak flux for the annular 2D solution normalised to 20 MWth.
ESTIMATE2_NOMINAL_FLUX_N_CM2_S: float = 1.5e12

ESTIMATE2_NOMINAL_POWER_MW: float = 20.0

# ---------------------------------------------------------------------------
# Combined control/shutdown bank design
# ---------------------------------------------------------------------------
# Central equivalent shutdown-bank geometry selected from 2D sweep:
# - rod radius widened from 10 cm to 50 cm (equivalent absorber volume)
# - stronger effective absorber increment in the inserted zone
ROD_RADIUS_CM: float = 50.0
ROD_DELTA_SIGMA_A_MAX_CM_INV: float = 0.25

# Clean-core operating point from 3 cm-mesh 2D solve (unrodded, x=0).
CLEAN_CORE_KEFF: float = 1.000199
CLEAN_CORE_BASE_EXCESS_PCM: float = 19.9

# ---------------------------------------------------------------------------
# 2D rod-worth scan: insertion fraction x → Δρ (pcm)
# ---------------------------------------------------------------------------
# Δρ(x) = ρ_pcm(k_rod(x)) − ρ_pcm(k_unrod)  where k_unrod = 1.000199
#
# x = 0.0 is forced to 0.0 by definition (reference against itself).
# Generated by running solve_2d at x = 0.0, 0.1, …, 1.0 with the current
# combined control/shutdown bank geometry (r_rod=50 cm, dSa_max=0.25 cm⁻¹).
#
# Full-insertion rod worth: −164.8 pcm relative to unrodded.
# Critical insertion (total ρ = 0): ~19.3 % insertion.
ROD_WORTH_X: tuple[float, ...] = (0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
ROD_WORTH_DELTA_RHO_PCM: tuple[float, ...] = (
    0.0, -7.2, -20.8, -41.0, -65.6, -92.2, -118.6, -141.4, -156.9, -163.5, -164.8
)

FULL_INSERTION_ROD_WORTH_PCM: float = 164.8
CRITICAL_INSERTION_PERCENT: float = 19.3
FULL_INSERTION_TOTAL_PCM: float = -144.9

# ---------------------------------------------------------------------------
# One-group material constants for the 2D r-z diffusion model
# ---------------------------------------------------------------------------
# Inner D2O moderator channel (pure heavy water, slightly spectrum-averaged)
D_MOD_INNER_CM: float = 1.25
SIGMA_A_MOD_INNER_CM_INV: float = 3.5e-4

# Homogenised fuel annulus: natural uranium rods + D2O moderator lattice.
# Fuel volume fraction v_f ≈ 1.77 %; Sigma_a inflated ~3× by resonance
# absorption relative to the 2200 m/s thermal-point macroscopic value.
D_FUEL_CM: float = 0.95
SIGMA_A_FUEL_CM_INV: float = 8.5e-3
NU_SIGMA_F_FUEL_CM_INV: float = 8.59e-3

# Outer D2O reflector (marginally higher temperature + trace impurities
# raise Sigma_a slightly above the inner moderator value)
D_REFL_CM: float = 1.15
SIGMA_A_REFL_CM_INV: float = 4.0e-4
